### ISSUE TITLE
second feature of the tool for fuzzing on urls is not working !

### ISSUE THREAD

**Issue by Gaurav-2000** [dwisiswant0/crlfuzz#14]
**Describe the bug**

**To Reproduce**

1. install crlfuzz

2. run crlfuzz -l

3. not giving any output just showing this 

 crlfuzz -l ~/Desktop/recon/urls.txt
   _____ _____ __    _____             
  |     | __  |  |  |   __|_ _ ___ ___ 
  |   --|    -|  |__|   __| | |- _|- _|
  |_____|__|__|_____|__|  |___|___|___|

      v1.4.0 - @dwisiswant0

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.

4.while you run the crlfuzz -u "http://test.com" 

working fine

5.  while subfinder target.com | crlfuzz

working fine

** it is expected to run tool while giving input as file**

[****](url
![Screenshot from 2020-11-29 00-16-56](https://user-images.githubusercontent.com/47737244/100533957-3d88bb00-31d8-11eb-9102-0e44b7a6f4de.png)
![Screenshot from 2020-11-29 00-16-54](https://user-images.githubusercontent.com/47737244/100533960-424d6f00-31d8-11eb-86bb-ddbca20e61f5.png)

)

**Environment (please complete the following information):**

- OS: [linux]
- OS version: [Linux kali 5.9.0-kali2-amd64 #1 SMP Debian 5.9.6-1kali1 (2020-11-11) x86_64 GNU/Linux
]
- CRLFuzz Version [crlfuzz --  v1.4.0]

**Comment by dwisiswant0** [comment]
Double check the location of the file, is it correct or not, whether there is any content or not, @Gaurav-2000.
