### ISSUE TITLE
Adding custom header breaks the tool

### ISSUE THREAD

**Issue by unstabl3** [dwisiswant0/crlfuzz#26]
Hi, :)
**Describe the bug**

While adding custom headers tools break.

**To Reproduce**

`cat live_targets.txt | crlfuzz -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0" `

`cat targets.txt | httpx | crlfuzz -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0" `

**Expected behavior**

The tool should able to add a custom header in every HTTP request.

**Environment (please complete the following information):**

- OS: tested in both Ubuntu and in kali
- OS version: 18.04 and 5.10.13-1kali1 (2021-02-08) x86_64
- CRLFuzz Version: CRLFuzz 1.4.0

**Additional context**

Below is the error log. 

```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x659cc9]

goroutine 40 [running]:
github.com/dwisiswant0/crlfuzz/pkg/crlfuzz.Scan(0xc0000f6480, 0x37, 0x0, 0x0, 0x0, 0x0, 0xc0000a0bf0, 0x1, 0x1, 0x0, ...)
        /root/go/pkg/mod/github.com/dwisiswant0/crlfuzz@v1.4.0/pkg/crlfuzz/crlfuzz.go:22 +0x3e9
github.com/dwisiswant0/crlfuzz/internal/runner.(*Options).run(0xc0000bea00, 0xc0000f6480, 0x37)
        /root/go/pkg/mod/github.com/dwisiswant0/crlfuzz@v1.4.0/internal/runner/runner.go:41 +0xb2
github.com/dwisiswant0/crlfuzz/internal/runner.New.func1(0xc000096180, 0xc0000bea00, 0xc0000b82e0)
        /root/go/pkg/mod/github.com/dwisiswant0/crlfuzz@v1.4.0/internal/runner/runner.go:22 +0x65
created by github.com/dwisiswant0/crlfuzz/internal/runner.New
        /root/go/pkg/mod/github.com/dwisiswant0/crlfuzz@v1.4.0/internal/runner/runner.go:20 +0xcc```

Let me know if any additional information required.
Take care,
unstabl3

**Comment by unstabl3** [comment]
FYI,

The tool works perfectly fine without "-H" flag.

**Comment by dwisiswant0** [comment]
Not sure exactly why this happened, you should try the latest version `v1.4.1` which I tested and had no problems.
