### ISSUE TITLE
Cant able to pass list in crlfuzz

### ISSUE THREAD

**Issue by kabilan1290** [dwisiswant0/crlfuzz#7]
Hey mate,

I tried curlfuzz with -l flag defined wordlist and theres a error in output.

└──╼ #crlfuzz -l /root/Desktop/domains.resolved.txt 

   _____ _____ __    _____             
  |     | __  |  |  |   __|_ _ ___ ___ 
  |   --|    -|  |__|   __| | |- _|- _|
  |_____|__|__|_____|__|  |___|___|___|

      v1.4.0 - @dwisiswant0

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.

All i get is blank result.

**Comment by dwisiswant0** [comment]
Hi @kabilan1290, please make sure the URL list begins with `http(s)`.

**Comment by kabilan1290** [comment]
Thanks !!
